version: '3'
services:
  app:
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG}
      - DJANGO_SETTINGS_MODULE=iot_Project.settings
    # command: uwsgi --http :8000 --socket /socket/api.sock --chmod-socket=666 --module _base.wsgi --master --processes 5 --threads 2
    # command: uwsgi --http :8000 --module _base.wsgi --master --processes 5 --threads 2
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

#  db:
#    image: mysql
#    restart: always
#    env_file:
#      - .env
#    ports:
#      - "3308:3307"
#    volumes:
#      - $HOME/Desktop/MySQL-Snippets/school.sql:/school.sql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: test_db
db:
  image: postgres:11.12
  env_file:
    - .env
  ports:
    - "5432:5432"
  volumes:
    - /home/mostafa/data/postgres:/var/lib/postgresql/data
  environment:
    - POSTGRES_DB=test_db
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root