# Generated by Django 3.2.9 on 2021-11-27 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_ID', models.CharField(max_length=100, unique=True)),
                ('Time_send', models.DateTimeField(auto_now=True)),
                ('HeartRate', models.CharField(max_length=100, null=True)),
                ('Temp', models.CharField(blank=True, max_length=100, null=True)),
                ('Auxiliary1', models.CharField(blank=True, max_length=100, null=True)),
                ('Auxiliary2', models.CharField(blank=True, max_length=100, null=True)),
                ('Auxiliary3', models.CharField(blank=True, max_length=100, null=True)),
                ('labeled', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
