# Generated by Django 3.2.9 on 2021-12-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pulse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pulse',
            name='labeled',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
