# Generated by Django 3.2.9 on 2021-11-23 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_of_device', models.CharField(max_length=1000, unique=True)),
                ('Time_send', models.DateTimeField(auto_now=True)),
                ('x', models.CharField(max_length=100)),
                ('y', models.CharField(max_length=100)),
                ('z', models.CharField(max_length=100)),
                ('roll', models.CharField(max_length=100)),
                ('pitch', models.CharField(max_length=100)),
                ('yaw', models.CharField(max_length=100)),
                ('psi', models.CharField(max_length=100, null=True)),
                ('theta', models.CharField(max_length=100, null=True)),
                ('phi', models.CharField(max_length=100, null=True)),
                ('labeled', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
