# Generated by Django 3.2.9 on 2021-11-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelo', '0002_alter_accelo_labeled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accelo',
            name='ID_of_device',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
