# Generated by Django 3.2.9 on 2021-12-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accelo', '0004_auto_20211206_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='accelo',
            name='Preprocessed',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
